services:
    db_test:
        image: postgres
        container_name: db_test
        restart: always
        ports:
            - 1234:5432
        env_file:
            - .env.test
        volumes:
            - pg:/var/lib/postgresql/data

    node_app_test:
        container_name: app_test
        build: .
        ports:
            - 5000:5000
        depends_on:
            - db_test
        env_file:
            - .env.test
volumes:
    pg:
